#library(tibble)
#codebook = sqlQuery(new_con,"select * from codebook_table;",stringsAsFactors=F)

con4 = odbcConnectAccess2007("S:/MIND/RESEARCH/STAAR/5- Database docs/STAAR Local Data Entry/STAAR-BehaviorDataEntry.mdb",readOnly=TRUE)
available_tables4 = sqlTables(con4)
#rm(available_tables4,con4)
con5 <- odbcConnectAccess2007("S:/MIND/RESEARCH/STAAR/5- Database docs/Data Master/STAAR Subject Tracking.accdb",readOnly=TRUE)
available_tables5 = sqlTables(con5)
new_con = odbcConnectAccess2007("S:/MIND/RESEARCH/APP/APP Database/2 - Data/APP-BehaviorDataEntry.mdb",readOnly=TRUE)
available_tables_new = sqlTables(new_con)
new_con2 = odbcConnectAccess2007("S:/MIND/RESEARCH/APP/APP Database/2 - Data/ParticpantTracking-Data.accdb",readOnly=TRUE)
available_tables_new2 = sqlTables(new_con2)
mri_con = odbcConnectAccess2007("S:/MIND/RESEARCH/APP/APP Database/2 - Data/MRI_Database.accdb",readOnly=TRUE)
available_tables_mri = sqlTables(mri_con)
med_con = odbcConnectAccess2007("S:/MIND/RESEARCH/APP/APP Database/2 - Data/APP_MedExamData.mdb",readOnly=TRUE)
available_tables_med = sqlTables(med_con)

# cast = sqldf("select cast(ccc_age/12 as int) from ccc")
# rm(cast)
