setwd("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing")

putting_together_all = function(){
  library(RODBC) #package for accessing access db
  library(sqldf)
  library(plyr)
  library(readxl)
  library(writexl)
  library(redcapAPI)
  #opening all the connections and packages
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Connection_List.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/REDCap_Connection.R")
  #all the functions
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Age_Calculation.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/ADI_functions.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Autoimmune_functions.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/outlier_adjustment.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/ADOS_functions.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/CDI_functions.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Converting_Individual_Items.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Converting_to_Char.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Merging_Study_Subjects.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Duplicate_Data.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Orphaned_Data.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Missing_Data.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/outlier_adjustment.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Prefix.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/REDCap_functions.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Single_Entry_Check.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/SQL_Statements.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Updating_Demographic_Info.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/VABS_functions.R")
  
  #all the scoring/processing scripts
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/ABAS/ABAS_Scoring.R")
  #source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/ADAMS/ADAMS_Scoring.R") -> no data currently available
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/ADI/ADI_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/ADIS/ADIS_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/ADOS/ADOS_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/AQC/AQC_Scoring.R")
  #source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/AQC/AQC_STAAR_Scoring.R") -> no data currently available
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CAT-Q/CAT_Q_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CBCL/CBCL_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CBQ/CBQ_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CCC/CCC_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CDI/CDI_WG_Scoring.R") 
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CDI/CDI_WS_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CELF/CELF4_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CELF/CELF5_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CGI/CGI_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CONNERS/CONNERS_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/CSHQ (aka Sleep)/CSHQ_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/DAS/DAS_EY_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/DAS/DAS_SA_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/DAS/DAS_Table_Combining.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Demographics/Demographic_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Diagnostic Consensus/Longitudinal_Diagnosis_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/DSM/DSM_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/EDI/EDI_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/EDQ/EDQ_Scoring.R")#having an error => certain columns must not be existing or sth "subscript out of bounds"
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/EOWPVT/EOWPVT3_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/EOWPVT/EOWPVT4_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/FQS/FQS_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/GORT/GORT_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Harter/Harter_Scoring.R")
  # source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Harter/Harter_Teen_Scoring.R")#redcap data exists -> need further processing and need to know which entry corresponds to which score
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/HPT/HPT_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/MASC/MASC_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Med/Autoimmune_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Med/DNA_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Med/GI_History_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Med/Physical_Exam_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Med/Tanner_Staging_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/MRI/TCV_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/MRI/Growth_Measurement_Processing.R")
  #source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/MRI/FreeSurfer(FS)_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/MRI/FPS_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/MRI/Mori_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/MRI/Scan_Details_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/MRI/DM_Status_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/MULLEN/Mullen_scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/NIH/NIH_Toolbox_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/PAL/PAL_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/PARS/PARS_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/PAS/PAS_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Petersen/Petersen_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/PPVT/PPVT3_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/PPVT/PPVT4_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/PRAS-ASD/PRAS_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/RBS/RBS_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Satisfaction/Satisfaction_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/SB5/SB5_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/SCARED/SCARED_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/SCQ/SCQ_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/SEQ/SEQ_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/SRS/SRS_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/SSP/SSP_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/SSP2/SSP2_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/STI/STI_Scoring.R")#redcap data exists -> same error as EDQ
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/SWAN/SWAN_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/TMCQ/TMCQ_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/TOWRE/TOWRE_Processing.R")
  # source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Vineland/VABS_Scoring.R") #certain redcap entries do not have certain items or scales...
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/WASI/WASI_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/WRAML/WRAML_Processing.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/YSR/YSR_Scoring.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/YTP/YTP_Scoring.R")
  
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Data Audit/Tracking_Table_Cleanup.R")
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Master_APP_Visits.R")
}
#source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Tracking_vs_DataEntry.R") -> manually run the script
source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Data Audit/Visit_Consolidation.R")
source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Summary IQ/Summary_IQ_Processing.R")
#closing all the connections
source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Functions/Closing_Connections.R")
rm(i,j,l)

source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/Data Audit/Flagging_Tables_Consolidation.R")

sending_data_to_mysql = function(){    
  #sending the tables to MySQL DB
  library("RMariaDB")
  library(keyring)
  tryCatch({
    mysql_pass = key_get('ACE',user_name='park')
    rm(mysql_pass)
  }, error=function(cond){key_set('ACE',user='park')})
  source("S:/MIND/RESEARCH/APP Behavior Data/ACE data R processing/ACE_db_connection.R")
}
